# -*- coding: utf-8 -*-
"""Lutsk Open.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7jYeFlc_SpnWtCYQDFaCsK9KozB-mQv

# Імпорт датасету та бібліотек
"""

# -*- coding: utf-8 -*-
"""Lutsk Open — утиліти для аналітики та експорту

Цей модуль було створено з Colab‑ноутбука і він містить функції для обробки
результатів турніру Lutsk Open: підготовки таблиць, побудови графіків і
експорту зображень гравців та дивізіонів.

Короткі вказівки для супроводу:
- Оригінальний ноутбук використовував Colab‑магії та інтерактивні виклики
    `display()`. Щоб зробити модуль безпечним при імпорті (наприклад для
    Sphinx/autodoc), інтерактивні та IO‑ділянки коду обгорнено прапором
    ``RUN_INTERACTIVE``.
- Для повного виконання pipeline встановіть ``RUN_INTERACTIVE = True`` і
    запускайте скрипт у середовищі з підключеним Drive та доступною
    утилітою ``wkhtmltoimage``. Для генерації документації залишайте
    ``RUN_INTERACTIVE = False``.

Автор: Baidiuk Anton DA-22
Проєкт: Telegram disc golf bot — аналітичні допоміжні функції
"""

# NOTE: the original notebook ran shell commands and installed packages.
# Those lines are commented out here; install externally when you need them.
# !pip install imgkit
# !apt-get update
# !which wkhtmltoimage
# !apt-get install -y wkhtmltopdf
# !pip install adjustText

import os
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import imgkit
from PIL import Image
from IPython.display import display, HTML

# When building docs, set RUN_INTERACTIVE = False to avoid executing
# interactive / Colab-specific code paths. Change to True to run end-to-end.
RUN_INTERACTIVE = False

# Minimal placeholders so the module is import-safe for Sphinx autodoc.
# These are safe defaults used only when `RUN_INTERACTIVE` is False.
df = pd.DataFrame(columns=[str(i) for i in range(1, 19)] + ['DIV', 'Round', 'Thru', 'Player', 'Tot'])
par = [3] * 18
o_par = [3] * 18
par_sum = sum(par)
o_par_sum = sum(o_par)
year = "2025"
tournament = "Lutsk Open"

# 🎨 Кольори результатів
score_colors = {
    'Ace': '#e8fc03',
    'Albatros': '#fcba03',
    'Eagle': '#008A05',
    'Birdie': '#00FF00',
    'Par': '#FFFFFF',
    'Bogey': '#fa11db',
    'Double Bogey+': '#800000'
}

# 🎨 Кольори дивізіонів
division_colors = {
    'MPO': '#ae41f2',
    'FPO': '#d55ced',
    'FA40': '#FF69B4',
    'FP40': '#FF69B4',
    'MP40': '#FFD700',
    'MA40': '#FFD700',
    'MA1': '#038cfc',
    'MA2': '#038cfc',
    'MA3': '#038cfc',
    'MA4': '#038cfc',
    'FA1': '#ec5739',
    'FA2': '#ec5739',
    'FA3': '#ec5739',
    'FA4': '#ec5739',
    'MJ18':'#0affef',
    'ALL': '#41f29d'
}
division_list = list(df['DIV'].unique())

def plot_color_legend(color_dict, title):
    """Побудувати легенду відповідності мітка → колір.

    Допоміжна функція створює компактну вертикальну легенду, яка
    візуально показує, які кольори відповідають яким міткам (типи
    результатів або дивізіони).

    Параметри
    - color_dict: словник мітка -> рядок кольору
    - title: заголовок фігури
    """
    fig, ax = plt.subplots(figsize=(8, len(color_dict) * 0.5))
    ax.set_xlim(0, 1)
    ax.set_ylim(0, len(color_dict))
    ax.axis('off')
    for i, (label, color) in enumerate(color_dict.items()):
        ax.add_patch(plt.Rectangle((0.05, i), 0.1, 0.8, color=color))
        ax.text(0.2, i + 0.4, label, va='center', fontsize=12)
    ax.set_title(title, fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.show()


# When running interactively (Colab) show color legends; skip during import/docs.
if RUN_INTERACTIVE:
    # 🔹 Візуалізація кольорів для результатів
    plot_color_legend(score_colors, 'Кольори результатів')

    # 🔸 Візуалізація кольорів для дивізіонів
    plot_color_legend(division_colors, 'Кольори дивізіонів')


def run_all(file_path: str | None = None, interactive: bool = RUN_INTERACTIVE):
    """Execute the full analytics pipeline.

    This function encapsulates the notebook's top-level logic: data loading,
    transformations, plotting, and export. It is intentionally safe to
    import by default — when ``interactive`` is False the function returns
    immediately without performing IO, plotting, or file writes.

    Parameters
    ----------
    file_path : str | None
        Optional path to the Excel file to load. If omitted the function
        will use the module-level ``df`` (useful when running inside
        Colab with Drive mounted).

    interactive : bool
        When False the function exits immediately (no IO or plots). Set
        to True to run the full pipeline.
    """
    if not interactive:
        return

    # Local imports and setup (kept inside function to avoid import-time IO)
    from IPython.display import display, HTML
    import matplotlib.patches as mpatches

    # If a file path is provided, load the Excel file from Drive/local FS.
    if file_path:
        loaded_df = pd.read_excel(file_path)
    else:
        loaded_df = df

    # Make a working copy and filter finished rounds
    working_df = loaded_df.copy()
    working_df = working_df[working_df['Thru'] == 'F']
    working_df = working_df[working_df['Round'] != 'PAR']

    # Створюємо DataFrame для відображення
    par_table = pd.DataFrame({
        'Тип': ['par', 'o_par'],
        'Значення': [str(par), str(o_par)],
        'Сума': [par_sum, o_par_sum]
    })
    display(HTML("<h3 style='color:#444;'>📊 Порівняння масивів PAR</h3>"))
    display(par_table)

    # Аналіз раунду — підготовка та стилізації
    holes_local = [str(i) for i in range(1, 19)]

    # Reuse module-level helpers but operate on `working_df` and `holes_local`.
    def style_row_local(row):
        return style_row(row)

    # 🧹 Копія df без 'Round' і 'Thru'
    df_clean = working_df.drop(columns=['Round', 'Thru']).copy()

    # ➕ Додаємо Tot і Score
    df_clean['Tot'] = df_clean[holes_local].sum(axis=1)
    df_clean['Score'] = df_clean.apply(
        lambda row: row['Tot'] - 60 if row['DIV'] == 'MPO' else row['Tot'] - 61,
        axis=1
    )

    # 🔢 Індексація з 1
    df_clean.index = range(1, len(df_clean) + 1)

    # 🖌️ Стилізація всієї таблиці
    styled_df = df_clean.style.apply(style_row_local, axis=1)

    styled_df = styled_df.set_table_styles([
        {'selector': 'th', 'props': [
            ('background-color', 'black'),
            ('color', 'white'),
            ('text-align', 'center'),
            ('border', '1px solid black')
        ]},
        {'selector': 'td', 'props': [
            ('text-align', 'center'),
            ('border', '1px solid black')
        ]}
    ]).set_properties(**{
        'color': 'black',
        'border-color': 'black'
    })

    # 📊 Відображення
    display(HTML("<h3 style='color:#444;'>📋 Повна таблиця всіх дивізіонів</h3>"))
    display(styled_df)

    # The remainder of the pipeline (grouping, plotting, export) follows
    # the same structure as the original notebook. For brevity we call the
    # helper functions already defined in the module and pass `working_df`.

    # Convert hole columns to numeric
    working_df[holes_local] = working_df[holes_local].apply(pd.to_numeric, errors='coerce').astype('Int64')

    # Ideal/horror/best/worst computations
    ideal_rounds = working_df.groupby(['Player', 'DIV'])[holes_local].min().reset_index()
    ideal_rounds['Tot'] = ideal_rounds[holes_local].sum(axis=1)
    ideal_rounds['Score'] = ideal_rounds.apply(calculate_score, axis=1)
    ideal_rounds_sorted = ideal_rounds.sort_values(by='Tot').reset_index(drop=True)
    ideal_rounds_sorted.index += 1

    styled_ideal = apply_table_style(ideal_rounds_sorted.style.apply(style_row, axis=1))
    display(HTML("<h3 style='color:#444;'>🏆 Загальна таблиця (усі дивізіони)</h3>"))
    display(styled_ideal)

    # Horror
    horror_rounds = working_df.groupby(['Player', 'DIV'])[holes_local].max().reset_index()
    horror_rounds['Tot'] = horror_rounds[holes_local].sum(axis=1)
    horror_rounds['Score'] = horror_rounds.apply(calculate_horror_score, axis=1)
    horror_rounds_sorted = horror_rounds.sort_values(by='Tot').reset_index(drop=True)
    horror_rounds_sorted.index += 1
    styled_horror_ALL = apply_table_style(horror_rounds_sorted.style.apply(style_row, axis=1))
    display(HTML("<h3 style='color:#444;'>💩 Загальна таблиця найгірших результатів (усі дивізіони)</h3>"))
    display(styled_horror_ALL)

    # Best
    best_real_sorted = (
        working_df.loc[working_df.groupby('Player')['Tot'].idxmin()]
        .reset_index(drop=True)
    )
    best_real_sorted['Score'] = best_real_sorted.apply(calculate_best_score, axis=1)
    best_real_sorted = best_real_sorted.sort_values(by='Tot').reset_index(drop=True)
    best_real_sorted.index += 1
    best_real_sorted = best_real_sorted[['Player', 'DIV'] + holes_local + ['Tot', 'Score']]
    styled_best_real_ALL = apply_table_style(best_real_sorted.style.apply(style_row, axis=1))
    display(HTML("<h3 style='color:#444;'>🌟 Найкращі реальні результати (усі дивізіони)</h3>"))
    display(styled_best_real_ALL)

    # Worst
    worst_real_sorted = (
        working_df.loc[working_df.groupby('Player')['Tot'].idxmax()]
        .reset_index(drop=True)
    )
    worst_real_sorted['Score'] = worst_real_sorted.apply(calculate_worst_real_score, axis=1)
    worst_real_sorted = worst_real_sorted.sort_values(by='Tot').reset_index(drop=True)
    worst_real_sorted.index += 1
    worst_real_sorted = worst_real_sorted[['Player', 'DIV'] + holes_local + ['Tot', 'Score']]
    styled_worst_real_ALL = apply_table_style(worst_real_sorted.style.apply(style_row, axis=1))
    display(HTML("<h3 style='color:#444;'>🕳️ Найгірші реальні результати (усі дивізіони)</h3>"))
    display(styled_worst_real_ALL)

    # Export setup
    imgkit_config_local = imgkit.config(wkhtmltoimage='/usr/bin/wkhtmltoimage')
    render_options_local = {
        'format': 'png',
        'encoding': 'UTF-8',
        'zoom': 2,
        'width': 1000
    }

    # Note: more plotting and export code can be added here following the
    # same pattern; omitted for brevity.

    return {
        'ideal': ideal_rounds_sorted,
        'horror': horror_rounds_sorted,
        'best': best_real_sorted,
        'worst': worst_real_sorted,
        'working_df': working_df
    }


# Only run when explicitly requested
if RUN_INTERACTIVE:
    run_all()

"""# Аналіз раунду

## Style
"""

holes = [str(i) for i in range(1, 19)]
# 🎨 Стилізація рядка
def style_row(row):
    """Повертає список CSS‑стилів для рядка DataFrame.

    Функція зіставляє значення результатів з кольорами з `score_colors`
    і призначає колір дивізіону для лівих стовпців. Призначена для
    використання з `pandas.Styler.apply(..., axis=1)`.

    Параметри
    - row: `pandas.Series` — рядок гравця з колонками для лунок
    """
    styles = [f'background-color: {division_colors.get(row["DIV"], "#B8860B")}'] * 2
    for i, hole in enumerate(holes):
        score, par_val = row[hole], par[i]
        if score == 1:
            color = score_colors['Ace']
        elif score == par_val - 2 and par_val > 3:
            color = score_colors['Eagle']
        elif score == par_val - 1:
            color = score_colors['Birdie']
        elif score == par_val - 3:
            color = score_colors['Albatros']
        elif score == par_val:
            color = score_colors['Par']
        elif score == par_val + 1:
            color = score_colors['Bogey']
        else:
            color = score_colors['Double Bogey+']
        styles.append(f'background-color: {color}')
 # 🖍️ Білий текст для Tot і Score
    styles += ['background-color: #222; color: white;', 'background-color: #222; color: white;']
    return styles

# 🖌️ Стиль таблиці
def apply_table_style(styler):
    """Застосувати єдиний стиль таблиці до екземпляра `pandas.Styler`.

    Налаштовує оформлення заголовків і клітинок, яке використовується у
    згенерованих таблицях та експортованих зображеннях.
    """
    return styler.set_table_styles([
        {'selector': 'th', 'props': [('background-color', 'black'), ('color', 'white'), ('text-align', 'center'), ('border', '1px solid black')]},
        {'selector': 'td', 'props': [('text-align', 'center'), ('border', '1px solid black')]}
    ]).set_properties(**{'color': 'black', 'border-color': 'black'})

# The interactive pipeline (data transforms, plotting and exports) has
# been moved into `run_all()` to avoid side effects during import.

"""## Export"""

# ⚙️ Конфігурація wkhtmltoimage

imgkit_config = imgkit.config(wkhtmltoimage='/usr/bin/wkhtmltoimage')  # ✅ об'єкт конфігурації
render_options = {
    'format': 'png',
    'encoding': 'UTF-8',
    'zoom': 2,
    'width': 1000
}

# 🌑 CSS для темної теми
css = '''
body {
    background-color: black;
    margin: 0;
    padding: 20px;
}
th, td {
    font-size: 13px;
    font-weight: bold;
    border: 0.5px solid #555;
    padding: 4px;
}
'''

# 🧱 Функція генерації PNG
def generate_player_png(row, filename, crop_right):
    """Згенерувати PNG для одного рядка гравця.

    Функція рендерить HTML‑таблицю з одним рядком (стилізовану через
    `pandas.Styler`), конвертує її в зображення за допомогою `imgkit`, обрізає
    праву частину і зберігає файл у папку гравця на Drive.

    Параметри
    - row: `pandas.Series` з даними гравця (має містити 'Player' і 'DIV')
    - filename: назва вихідного файлу (наприклад 'best.png')
    - crop_right: кількість пікселів для обрізки правої сторони
    """
    player = row['Player']
    div = row['DIV']
    base_path = f"/content/drive/MyDrive/dg/{year}/{tournament}/{div}"
    player_folder = os.path.join(base_path, player)
    os.makedirs(player_folder, exist_ok=True)

    file_path = os.path.join(player_folder, filename)
    player_df = pd.DataFrame([row]).reset_index(drop=True)

    styled = player_df.style.apply(style_row, axis=1).set_table_styles([
        {'selector': 'th', 'props': [
            ('background-color', 'black'),
            ('color', 'white'),
            ('text-align', 'center'),
            ('border', '0.5px solid #555'),
            ('padding', '4px'),
            ('font-size', '13px'),
            ('font-weight', 'bold')
        ]},
        {'selector': 'td', 'props': [
            ('text-align', 'center'),
            ('border', '0.5px solid #555'),
            ('padding', '4px'),
            ('font-size', '13px'),
            ('font-weight', 'bold')
        ]}
    ])

    html_str = f"<html><head><style>{css}</style></head><body>{styled.to_html()}</body></html>"

    imgkit.from_string(html_str, file_path, config=imgkit_config, options=render_options)

    with Image.open(file_path) as im:
        width, height = im.size
        cropped = im.crop((10, 10, width - crop_right, height - 10))
        cropped.save(file_path)

# Note: per-round configurations and export loops run inside `run_all()`.
round_configs = []

def generate_table_png(df, filename, crop_right, div_name):
    """Зрендерити і зберегти повну таблицю як PNG.

    Параметри
    - df: `pandas.DataFrame` для рендерингу (стилізується всередині)
    - filename: ім'я вихідного файлу
    - crop_right: пікселі для обрізки правого краю
    - div_name: назва дивізіону для вибору папки виводу
    """
    base_path = f"/content/drive/MyDrive/dg/{year}/{tournament}/{div_name}"
    os.makedirs(base_path, exist_ok=True)

    file_path = os.path.join(base_path, filename)

    # 🔧 Стилізація через style_row — застосовується до всіх колонок
    styled = df.style.apply(style_row, axis=1).set_table_styles([
        {'selector': 'th', 'props': [
            ('background-color', 'black'),
            ('color', 'white'),
            ('text-align', 'center'),
            ('border', '0.5px solid #555'),
            ('padding', '4px'),
            ('font-size', '13px'),
            ('font-weight', 'bold')
        ]},
        {'selector': 'td', 'props': [
            ('text-align', 'center'),
            ('border', '0.5px solid #555'),
            ('padding', '4px'),
            ('font-size', '13px'),
            ('font-weight', 'bold')
        ]}
    ])

    html_str = f"<html><head><style>{css}</style></head><body>{styled.to_html()}</body></html>"
    imgkit.from_string(html_str, file_path, config=imgkit_config, options=render_options)

    with Image.open(file_path) as im:
        width, height = im.size
        cropped = im.crop((10, 10, width - crop_right, height - 10))
        cropped.save(file_path)


# Interactive exports and per-player PNG generation have been moved into
# the `run_all()` function to keep module import-time side effects minimal.

"""# Buskets

# Загальна функція
"""

import os
#holes = list(range(1, 19))  # [1, 2, ..., 18]
holes = [str(i) for i in range(1, 19)]

def plot_division_pie_charts(filtered_df, par, holes, title, div_name, year, tournament):
    """Побудувати і зберегти сітку кругових діаграм розподілу результатів по лунках.

    Групує підрахунки по категоріях результатів (Ace, Birdie, Par тощо)
    для кожної лунки і малює одну діаграму на лунку. Результат зберігається
    у папці, визначеній параметрами `year`, `tournament` і `div_name`.

    Параметри
    - filtered_df: DataFrame, відфільтрований за дивізіоном або піднабором
    - par: послідовність значень par для кожної лунки
    - holes: список імен колонок лунок (рядки у вигляді рядків)
    - title: заголовок фігури
    - div_name: назва папки для збереження
    - year, tournament: використовуються для побудови шляху збереження
    """
    fig, axs = plt.subplots(3, 6, figsize=(20, 10), facecolor='#000000')
    axs = axs.flatten()

    for i, hole in enumerate(holes):
        ax = axs[i]
        scores = filtered_df[hole].astype(int)
        par_val = par[i]

        score_counts = {
            'Ace': (scores == 1).sum(),
            'Albatros': (scores == par_val - 3).sum(),
            'Eagle': ((scores == par_val - 2) & (par_val > 3)).sum(),
            'Birdie': (scores == par_val - 1).sum(),
            'Par': (scores == par_val).sum(),
            'Bogey': (scores == par_val + 1).sum(),
            'Double Bogey+': (scores >= par_val + 2).sum()
        }

        filtered_scores = {k: v for k, v in score_counts.items() if v > 0}
        values = list(filtered_scores.values())
        labels = list(filtered_scores.keys())
        used_colors = [score_colors[l] for l in labels]

        wedges, texts = ax.pie(
            values,
            colors=used_colors,
            startangle=90,
            wedgeprops=dict(width=0.5, edgecolor='black')
        )

        total = sum(values)
        for w, v in zip(wedges, values):
            angle = (w.theta2 + w.theta1) / 2
            x = 0.75 * np.cos(np.deg2rad(angle))
            y = 0.75 * np.sin(np.deg2rad(angle))
            pct = f'{(v / total) * 100:.0f}%'
            ax.text(x, y, pct, ha='center', va='center', color='black', fontsize=9, fontweight='bold')

        avg_score = scores.mean()
        ax.text(0, 0, f'{avg_score:.1f}', ha='center', va='center', color='white', fontsize=20, fontweight='bold')
        ax.set_title(f'Кошик {hole}\nPar {par_val}', color='white', fontsize=15)
        ax.set_aspect('equal')

    fig.suptitle(title, color='white', fontsize=18)

    legend_patches = [
        plt.Line2D([0], [0], marker='o', color='w', label=label,
                   markerfacecolor=score_colors[label], markersize=10)
        for label in score_colors if label in labels
    ]
    fig.legend(handles=legend_patches, loc='lower center', ncol=4, fontsize=12)

    plt.tight_layout(rect=[0, 0.05, 1, 0.95])

    # 📁 Створення директорії та збереження
    folder_path = f"/content/drive/MyDrive/dg/{year}/{tournament}/{div_name}"
    os.makedirs(folder_path, exist_ok=True)
    file_path = os.path.join(folder_path, f"holes_avg.png")
    fig.savefig(file_path, dpi=300, bbox_inches='tight', facecolor='#000000')
    plt.close(fig)

if RUN_INTERACTIVE:
    for div in division_list:
        current_par = par if div == 'MPO' else o_par

        plot_division_pie_charts(
            filtered_df=df[df['DIV'] == div],
            par=current_par,
            holes=holes,
            title=f'Розподіл результатів по лунках ({div})',
            div_name=div,
            year=year,
            tournament=tournament
        )

    plot_division_pie_charts(
        filtered_df=df,
        par=par,
        holes=holes,
        title='Розподіл результатів по лунках (усі дивізіони)',
        div_name='ALL',
        year=year,
        tournament=tournament
    )

def get_division_stats(df, par_list, holes):
    """Обчислити статистику по лунках для дивізіону.

    Повертає `DataFrame`, індексований метриками (Avg, Ace, Albatros, ...),
    де кожен стовпець відповідає конкретній лунці з відповідними значеннями.
    """
    stats = {
        'Metric': ['Avg', 'Ace', 'Albatros', 'Eagle', 'Birdie', 'Par', 'Bogey', 'Dbl+']
    }

    for i, hole in enumerate(holes):
        if hole not in df.columns:
            continue

        scores = df[hole].dropna().astype(int)
        par_val = par_list[i]

        stats[f'Hole {hole}'] = [
            round(scores.mean(), 2),                         # Avg
            (scores == 1).sum(),                             # Ace
            (scores == par_val - 3).sum(),                   # Albatros
            ((scores == par_val - 2) & (par_val > 3)).sum(), # Eagle
            (scores == par_val - 1).sum(),                   # Birdie
            (scores == par_val).sum(),                       # Par
            (scores == par_val + 1).sum(),                   # Bogey
            (scores >= par_val + 2).sum()                    # Double Bogey+
        ]
    return pd.DataFrame(stats).set_index('Metric')
if RUN_INTERACTIVE:
    division_stats = []

    for div in df['DIV'].unique():
        div_df = df[df['DIV'] == div]
        current_par = par if div == 'MPO' else o_par
        stats = get_division_stats(div_df, current_par, holes)
        stats.index = [f'{div} {i}' for i in stats.index]
        division_stats.append(stats)

    full_table = pd.concat(division_stats) if division_stats else pd.DataFrame()
    display(HTML("<h3 style='color:#444;'>📊 Статистика по дивізіонах</h3>"))
    display(full_table)

# 📊 Функція для обчислення середнього
def get_avg(df, par_list):
    """Обчислити середній результат по кожній лунці для заданого DataFrame.

    Повертає `pandas.Series`, індексований іменами лунок.
    """
    return pd.Series([df[hole].astype(int).mean() for hole in holes], index=holes)

# 📐 Функція для обчислення відсотків
def compute_percent(avg, par):
    """Перетворити середні результати у відсотки від par (100 = рівно par).

    `avg` та `par` повинні бути сумісними для операції поелементного ділення
    (наприклад, `Series` і список однакової довжини).
    """
    return (avg / par) * 100

if RUN_INTERACTIVE:
    # 📋 Збір середніх по всіх дивізіонах
    avg_by_div = {}
    for div in df['DIV'].unique():
        div_df = df[df['DIV'] == div]
        avg_by_div[div] = compute_percent(get_avg(div_df, par), par).round(1)

    # 📊 Додавання загального середнього
    avg_by_div['ALL'] = compute_percent(get_avg(df, par), par).round(1)

    # 📦 Побудова таблиці
    percent_table = pd.DataFrame(avg_by_div).T

    # 📋 Вивід
    display(percent_table)

    for division in percent_table.index:
        sorted_percent = percent_table.loc[division].sort_values(ascending=True)

        fig, ax = plt.subplots(figsize=(12, 6), facecolor='black')

        # 🔢 Позиції по осі X
        x_pos = np.arange(len(sorted_percent))

        # 📊 Побудова барів
        bars = ax.bar(x_pos, sorted_percent.values, color=division_colors[division])

        # 🏷️ Підписи над барами
        for bar, value in zip(bars, sorted_percent.values):
            ax.text(bar.get_x() + bar.get_width()/2, value + 1,
                    f'{value:.1f}%', ha='center', va='bottom', color='white', fontsize=9)

        # 💚 Лінія на 100%
        ax.axhline(100, color='lime', linestyle='--', linewidth=3)

        # 🧾 Підписи осі X
        ax.set_xticks(x_pos)
        ax.set_xticklabels(sorted_percent.index, color='white', fontsize=10)

        # 📌 Оформлення
        ax.set_title(f'Рейтинг складності лунок ({division})', color='white', fontsize=14)
        ax.set_xlabel('Лунка', color='white')
        ax.set_ylabel('% від par', color='white')
        ax.tick_params(colors='white')
        ax.set_facecolor('black')
        fig.patch.set_facecolor('black')
        ax.set_ylim(60, max(sorted_percent.values.max() + 10, 110))
        ax.grid(axis='y', linestyle='--', alpha=0.3, color='white')
        plt.tight_layout()

        # 📁 Збереження на диск
        folder_path = f"/content/drive/MyDrive/dg/{year}/{tournament}/{division}"
        os.makedirs(folder_path, exist_ok=True)
        file_path = os.path.join(folder_path, f"holes.png")
        fig.savefig(file_path, dpi=300, bbox_inches='tight', facecolor='black')
        plt.close(fig)
else:
    # Ensure names exist so later guarded blocks referencing `percent_table` don't fail
    percent_table = pd.DataFrame()

# 🔢 Дані
holes = [str(i) for i in range(1, 19)]
group1 = holes[:9]   # Лунки 1–9
group2 = holes[9:]   # Лунки 10–18
width = 0.15         # трохи вужчі стовпчики
spacing = 0.3        # відстань між групами

if RUN_INTERACTIVE:
    # 📊 Побудова графіків
    fig, axes = plt.subplots(1, 2, figsize=(20, 10), facecolor='black')
    axes = axes.flatten()

    groups = [group1, group2]
    titles = ['Лунки 1–9', 'Лунки 10–18']

    for ax, group, title in zip(axes, groups, titles):
        base_y = np.arange(len(group)) * (1 + spacing)  # розтягнуті позиції по Y
        divisions = percent_table.index

        for i, division in enumerate(divisions):
            values = percent_table.loc[division][group].values
            offset = (i - len(divisions)/2) * width
            color = division_colors.get(division, '#B8860B')

            bars = ax.barh(base_y + offset, values, height=width, label=division, color=color)

            # Підписи значень
            for bar, val in zip(bars, values):
                if val == 0:
                    continue
                ax.text(val + 1, bar.get_y() + bar.get_height()/2,
                        f'{val:.0f}%', va='center', ha='left', color='white', fontsize=8)

        # 💚 Лінія на 100%
        ax.axvline(100, color='lime', linestyle='--', linewidth=1.5)

        # Оформлення
        ax.set_yticks(base_y)
        ax.set_yticklabels(group, color='white')
        ax.set_ylabel('Лунка', color='white')
        ax.set_xlabel('% від par', color='white')
        ax.set_title(title, color='white', fontsize=16)
        ax.set_facecolor('black')
        ax.tick_params(colors='white')
        ax.set_xlim(60, max(percent_table[group].max().max() + 10, 115))
        ax.grid(axis='x', linestyle='--', alpha=0.3, color='white')

    # 🖍️ Легенда
    fig.legend(loc='lower center', ncol=len(divisions), facecolor='black',
               edgecolor='white', labelcolor='white', fontsize=12)

    plt.tight_layout(rect=[0, 0.05, 1, 0.95])
    plt.show()

holes = [str(i) for i in range(1, 19)]


player_scores = df[['Player', 'DIV'] + holes].copy()

# 🔁 Групуємо по гравцю та дивізіону
player_avg = (
    player_scores
    .groupby(['Player', 'DIV'])[holes]
    .mean()
    .round(2)
    .reset_index()
)

if RUN_INTERACTIVE:
    display(player_avg)

if RUN_INTERACTIVE:
    import os

    # 🎯 Обчислення середніх по гравцях
    scores = df[['Player', 'DIV'] + holes].copy()
    player_avg = (
        scores
        .groupby(['Player', 'DIV'])[holes]
        .mean()
        .round(2)
        .reset_index()
    )

    # 🧷 Додаємо мітку з дивізіоном до імені
    player_avg['Label'] = player_avg['Player'] + ' (' + player_avg['DIV'] + ')'
    player_avg.set_index('Label', inplace=True)

    # 📁 Папка для збереження
    output_folder = f"/content/drive/MyDrive/dg/{year}/{tournament}/ALL"
    os.makedirs(output_folder, exist_ok=True)

    # 📊 Побудова графіків
    for hole in holes:
        # 🔁 Сортування по зростанню
        top_hole = player_avg[[hole, 'DIV']].sort_values(by=hole, ascending=True)
        labels = top_hole.index
        values = top_hole[hole]
        colors = top_hole['DIV'].apply(lambda div: division_colors.get(div, '#B8860B'))

        fig, ax = plt.subplots(figsize=(10, 8), facecolor='black')
        bars = ax.barh(labels, values, color=colors)

        # 🏷️ Підписи значень
        for bar, value in zip(bars, values):
            ax.text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2,
                    f'{value:.2f}', va='center', ha='left', color='white', fontsize=9)

        # 🎨 Оформлення
        ax.set_title(f'Кошик {hole} — Середній результат', color='white', fontsize=14)
        ax.set_xlabel('Середній результат', color='white')
        ax.set_ylabel('Гравець (дивізіон)', color='white')
        ax.tick_params(colors='white')
        ax.set_facecolor('black')
        fig.patch.set_facecolor('black')
        ax.invert_yaxis()
        plt.grid(axis='x', linestyle='--', alpha=0.3, color='white')
        plt.tight_layout()

        # 💾 Збереження графіка
        file_path = os.path.join(output_folder, f"{hole}.png")
        fig.savefig(file_path, dpi=300, bbox_inches='tight', facecolor='black')
        plt.close(fig)

import os

# 🧮 Відхилення гравців у %
def get_player_percent_deviation(df, par_list, holes):
    """Обчислити відхилення гравця у відсотках від par для кожної лунки.

    Повертає `DataFrame`, де рядки — гравці, колонки — лунки, а значення —
    відсоткове відхилення ((avg - par) / par * 100).
    """
    players = df['Player'].unique()
    percent_dev = {}
    par_series = pd.Series(par_list, index=holes)

    for player in players:
        scores = df[df['Player'] == player][holes].astype(int)
        avg_scores = scores.mean()
        deviation = ((avg_scores - par_series) / par_series * 100).round(0)  # ⬅️ округлення до 0 знаків
        percent_dev[player] = deviation

    return pd.DataFrame(percent_dev).T


# 🎨 Колір для таблиці
def style_deviation_table(df):
    """Повернути стилізований `pandas.Styler`, який фарбує відсоткові відхилення.

    Клітинки заливуються зеленим для від'ємних відхилень (краще за par),
    золотим — для невеликих відхилень, та червоним — для значних позитивних
    відхилень.
    """
    def color_cell(val):
        if pd.isna(val): return ''
        if val < 0:
            intensity = min(abs(val) / 15, 1)
            green = int(255 - intensity * 120)
            return f'background-color: rgb({green}, 255, {green}); color: black'
        elif val < 10:
            return 'background-color: gold; color: black'
        else:
            red_intensity = min(val / 20, 1)
            red = int(255 * red_intensity)
            return f'background-color: rgb(255, {255 - red}, {255 - red}); color: black'
    return df.round(1).style.applymap(color_cell)

# 🎨 Колір для графіка
def get_bar_color(val):
    """Повернути RGB-кортеж, відповідний для стовпчика з відсотковим значенням.

    Від'ємні значення — зеленуваті, близькі до нуля — золотисті, великі
    позитивні — з відтінком червоного.
    """
    if val < 0:
        intensity = min(abs(val) / 15, 1)
        green = 1.0  # максимально яскравий зелений
        red = (1 - intensity * 0.5)
        return (red, green, red)
    elif val < 10:
        return (1.0, 0.84, 0.0)  # gold
    else:
        red_intensity = min(val / 20, 1)
        green = 1.0 - red_intensity
        return (1.0, green, green)


def plot_player_deviation(player_percent_df, year, tournament, df):
    """Побудувати графіки відхилень у відсотках для кожного гравця і зберегти їх.

    Для кожного гравця з `player_percent_df` створює стовпчикову діаграму
    відхилень по лунках і зберігає зображення у папку, визначену
    параметрами `year` і `tournament`.
    """
    for player in player_percent_df.index:

        if pd.isna(player):
            continue

        scores = player_percent_df.loc[player].round(0)
        x = np.arange(len(scores))
        bar_colors = [get_bar_color(val) for val in scores.values]

        fig, ax = plt.subplots(figsize=(10, 4), facecolor='black')
        bars = ax.bar(x, scores.values, color=bar_colors)

        ax.axhline(0, color='lime', linestyle='--', linewidth=2)

        for i, val in enumerate(scores):
            if val == 0:
                continue
            offset = 1 if val > 0 else -3
            ax.text(i, val + offset, f'{val:+.0f}%', ha='center', color='white', fontsize=8)

        ax.set_xticks(x)
        ax.set_xticklabels(scores.index, color='white', fontsize=9)
        ax.set_title(f'Відхилення від PAR у % — {player}', color='white', fontsize=12)
        ax.set_ylabel('Відхилення (%)', color='white', fontsize=10)
        ax.set_xlabel('Лунка', color='white', fontsize=10)
        ax.tick_params(colors='white')
        ax.set_facecolor('black')
        fig.patch.set_facecolor('black')
        plt.grid(axis='y', linestyle='--', alpha=0.3, color='white')
        plt.tight_layout()

        player_rows = df[df['Player'] == player]
        if not player_rows.empty:
            division = player_rows['DIV'].iloc[0]
        else:
            division = "Unknown"

        folder_path = f"/content/drive/MyDrive/dg/{year}/{tournament}/{division}/{player}"
        os.makedirs(folder_path, exist_ok=True)
        file_path = os.path.join(folder_path, "percent.png")

        fig.savefig(file_path, dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
        plt.show()  # ⬅️ Додати для відображення графіка
        plt.close(fig)


        fig.savefig(file_path, dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
        plt.close(fig)



# 🚀 Запуск
player_percent_df = get_player_percent_deviation(df, par, holes)

if RUN_INTERACTIVE:
    display(HTML("<h3 style='color:#444;'>🎯 Відхилення гравців у % від par (забарвлена таблиця)</h3>"))
    display(style_deviation_table(player_percent_df))

    plot_player_deviation(player_percent_df, year, tournament, df)

if RUN_INTERACTIVE:
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    from matplotlib.cm import ScalarMappable
    # 🔢 Лунки
    hole_cols = [str(i) for i in range(1, 19)]

    # 📥 Очистка та підготовка
    df = df[pd.to_numeric(df["Round"], errors="coerce").notna()].copy()
    df["Round"] = df["Round"].astype(int)

    # ✅ Перевірка наявності лунок
    missing = [col for col in hole_cols if col not in df.columns]
    if missing:
        print("❌ Відсутні колонки:", missing)
    else:
        # 🔧 Преобразування лунок у числовий формат
        df[hole_cols] = df[hole_cols].apply(pd.to_numeric, errors='coerce')


    # 🎨 Колірна карта
    cmap = plt.get_cmap('viridis')  # або 'plasma', 'inferno', 'magma', 'cividis', 'coolwarm', 'Greens'


    # 🔢 Лунки
    hole_cols = [str(i) for i in range(1, 19)]

    # 📊 Нестабільність за логарифмом
    grouped = df.groupby("Player")[hole_cols]

    def player_instability_log(scores):
        means = scores.mean()
        log_dev = np.log1p(np.abs(scores - means))
        deltas = log_dev.sum()
        """Compute a small 'instability' metric per player.

        This function implements the notebook's heuristic using log deviations
        from per-hole means. It returns a Series with per-hole values and an
        extra field 'Instab / (×Count × 5.55)' holding the aggregated metric.
        """
        count_below_1 = (deltas < 1).sum()
        total_instability = deltas.sum()
        count_times_555 = count_below_1 * 0.0555 if count_below_1 > 0 else None
        final_division = total_instability / count_times_555 if count_times_555 else None

        deltas["Instab / (×Count × 5.55)"] = final_division
        return deltas

    instability_df = grouped.apply(player_instability_log).reset_index()

    # 📊 Дані для графіка
    players = df['Player'].unique()
    metric_dict = dict(zip(instability_df["Player"], instability_df["Instab / (×Count × 5.55)"]))

    # ⚙️ Параметри парів
    par_sum = sum(par)  # ⚠️ переконайся, що список par існує і має 18 значень
    ideal_total = par_sum * 3

    plot_data = []

    for player_name in players:
        rounds = df[df["Player"] == player_name].copy()

        try:
            total_sum = rounds["Tot"].sum()
            division = rounds["DIV"].iloc[0]
            metric_value = metric_dict.get(player_name)
            if metric_value is not None:
                x_value = total_sum - ideal_total  # 🔁 Відхилення від ідеального Tot
                plot_data.append((player_name, x_value, metric_value, division))
        except Exception:
            continue

    # 🧹 Видалити точку з іменем "Michael Aaron"
    plot_data = [entry for entry in plot_data if entry[0] != "Eduard Shalaiko"]


    # 🎨 Побудова графіка
    fig, ax = plt.subplots(figsize=(10, 6))
    fig.patch.set_facecolor('black')
    ax.set_facecolor('none')

    if plot_data:
        names, totals, metrics, divisions = zip(*plot_data)
        colors = [division_colors.get(div, "#888888") for div in divisions]
        ax.scatter(totals, metrics, c=colors, s=40)

        # 🏷️ Імена над точками з індивідуальним зсувом
        for name, x, y, _ in plot_data:
            # 🔧 Зсуви за іменами
            if name in [ "Oleksandr Lapchuk"]:
                y_offset = -13
                x_offset = 0
            elif name == "Oleksandr Romanenko":
                y_offset = -13
                x_offset = 0
            elif name == "Vadym Novikov":
                y_offset = -13
                x_offset = 0
            elif name == "Dima Boiko":
                y_offset = -13
                x_offset = 0
            elif name == "Ivan Golub":
                y_offset = -13
                x_offset = 0
            else:
                y_offset = 4
                x_offset = 0

            # 🏷️ Відображення тексту з урахуванням зсувів
            ax.text(x + x_offset, y + y_offset, name, fontsize=8, color='white', ha='center', va='bottom')

        # 📘 Легенда дивізіонів
        unique_divisions = sorted(set(divisions))
        legend_elements = [mpatches.Patch(color=division_colors.get(div, "#888888"), label=div) for div in unique_divisions]
        legend = ax.legend(handles=legend_elements, title="Дивізіон", loc="upper right", fontsize=10,
                           title_fontsize=11, facecolor='black', edgecolor='white')
        for text in legend.get_texts():
            text.set_color('white')
        legend.get_title().set_color('white')

        # 🧽 Прибрати y-вісь
        ax.set_yticks([])

        from matplotlib.colors import LinearSegmentedColormap

        # 🌈 Кастомна колірна карта: салатовий → жовтий → червоний
        custom_cmap = LinearSegmentedColormap.from_list("green_red_fade", ["#7CFC00", "#FFFF00", "#FF0000"])

        # 🌈 Градієнтний фон осі Y
        ax_limits = ax.get_ylim()
        gradient = np.linspace(0, 1, 256).reshape(256, 1)
        ax.imshow(gradient, extent=[ax.get_xlim()[0], ax.get_xlim()[1], ax_limits[0], ax_limits[1]],
                  aspect='auto', cmap=custom_cmap, alpha=0.3, origin='lower', zorder=0)


        # 📌 Фінальне оформлення
        ax.set_xlabel("Фінальний результат", fontsize=12, color='white')
        ax.set_title("Стабільність гравців", fontsize=14, color='white')
        ax.tick_params(colors='white')
        ax.grid(False)
        ax.set_ylabel("Стабільність", fontsize=12, color='white')
        plt.tight_layout()
        plt.show()

        # 📁 Папка для збереження
        output_folder = f"/content/drive/MyDrive/dg/{year}/{tournament}/ALL"
        os.makedirs(output_folder, exist_ok=True)

        # 💾 Збереження графіка
        file_path = os.path.join(output_folder, "stability.png")
        fig.savefig(file_path, dpi=300, bbox_inches='tight', facecolor='black')